# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgChtmk6GfjuEYFn0f2buL0MR22PfUVV
"""

import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import joblib

# MODEL MLP
class MLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 3)
        )

    def forward(self, x):
        return self.fc(x)

# LOAD MODEL & SCALER
model = MLP(input_dim=9)
model.load_state_dict(torch.load("model_mlp.pth", map_location=torch.device("cpu")))
model.eval()

scaler = joblib.load("scaler.pkl")

# STREAMLIT UI
st.title("Prediksi Waktu Optimal Belajar")
st.write("Aplikasi Deep Learning (MLP)")

st.subheader("Input Data")

jam_tidur = st.selectbox("Jam Tidur", [
    "21.00-22.00", "22.01-23.00", "23.01-00.00", "00.01-01.00", "> 01.00"
])

durasi_tidur = st.selectbox("Durasi Tidur", [
    "< 5 jam", "5-6 jam", "6-7 jam", "7-8 jam", "> 8 jam"
])

durasi_belajar = st.selectbox("Durasi Belajar", [
    "< 1 jam", "1-2 jam", "2-3 jam", "3-4 jam", "> 4 jam"
])

jam_belajar = st.selectbox("Jam Belajar", [
    "05.00-10.59", "11.00-16.59", "17.00-00.59"
])

gangguan = st.slider("Tingkat Gangguan", 1, 5)
durasi_hp = st.selectbox("Durasi HP/Laptop", [
    "< 2 jam", "2-4 jam", "4-6 jam", "> 6 jam"
])

coffee = st.selectbox("Konsumsi Kopi", ["Tidak", "Ya"])
mood = st.slider("Mood", 1, 5)
produktivitas = st.slider("Produktivitas", 1, 5)

# ENCODING
encode_jam_tidur = {
    "21.00-22.00": 0, "22.01-23.00": 1, "23.01-00.00": 2,
    "00.01-01.00": 3, "> 01.00": 4
}

encode_durasi_tidur = {
    "< 5 jam": 0, "5-6 jam": 1, "6-7 jam": 2,
    "7-8 jam": 3, "> 8 jam": 4
}

encode_durasi_belajar = {
    "< 1 jam": 0, "1-2 jam": 1, "2-3 jam": 2,
    "3-4 jam": 3, "> 4 jam": 4
}

encode_jam_belajar = {
    "05.00-10.59": 0, "11.00-16.59": 1, "17.00-00.59": 2
}

encode_hp = {
    "< 2 jam": 0, "2-4 jam": 1, "4-6 jam": 2, "> 6 jam": 3
}

encode_coffee = {"Tidak": 0, "Ya": 1}

# Prediksi
if st.button("Prediksi"):
    data = np.array([[
        encode_jam_tidur[jam_tidur],
        encode_durasi_tidur[durasi_tidur],
        encode_durasi_belajar[durasi_belajar],
        encode_jam_belajar[jam_belajar],
        gangguan,
        encode_hp[durasi_hp],
        encode_coffee[coffee],
        mood,
        produktivitas
    ]])

    data_scaled = scaler.transform(data)
    data_tensor = torch.tensor(data_scaled, dtype=torch.float32)

    with torch.no_grad():
        output = model(data_tensor)
        pred = torch.argmax(output, dim=1).item()

    label_map = {
        0: "Pagi (05.00-10.59)",
        1: "Siang (11.00-16.59)",
        2: "Malam (17.00-00.59)"
    }

    st.success(f"Waktu optimal belajar Anda adalah: **{label_map[pred]}**")